name: OCPL Configuration Management Standards Check (Shared)

on:
  pull_request:

#cancel previous runs for this ref
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:

  #commitlint commitlint
  commitlint_remote:
    # The github context isn't recognized in the ref for the called workflow,
    # so we'll have  to leave that one hard-coded for now.
    #uses: nciocpl/.github/.github/workflows/ocpl_cm_standards_check.yml@workflow/v4
    uses: nciocpl/.github/.github/workflows/ocpl_cm_standards_check.yml@ticket/14-module-fix
    with:
      config_ref: '${{ github.head_ref }}'

  test:
    name: Test commitlint rules
    runs-on: ubuntu-latest
    steps:

      - name: Checkout branch
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/jod'

      - name: Install commitlint
        run: npm install -g commitlint

      - name: Run tests
        run: |
          ./test.sh